# HTTP -> HTTPS 重定向
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name goldnews-analysis.easypus.com;
    return 301 https://$host$request_uri;
}

# HTTPS
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name goldnews-analysis.easypus.com;
    ssl_certificate /etc/letsencrypt/live/goldnews-analysis.easypus.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/goldnews-analysis.easypus.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /root/workspace/project/financial-news-analysis/web_display;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location /data/ {
        add_header Cache-Control "no-cache";
    }
}
